[package]
name = "ashell"
description = "Barely customizable Wayland status bar for Hyprland compositor."
homepage = "https://github.com/MalpenZibo/ashell"
version = "0.2.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "wgpu", "advanced"] }
iced_runtime = { version = "0.13.1", features = ["multi-window"] }
iced_layershell = "0.9.6"
chrono = "0.4"
hyprland = { git = "https://github.com/MalpenZibo/hyprland-rs" }
serde = "1.0"
sysinfo = "0.32"
tokio = { version = "1", features = ["full"] }
zbus = "5"
libpulse-binding = { version = "2.28", features = ["pa_v15"] }
inotify = "0.11"
log = { version = "0.4", features = ["serde"] }
flexi_logger = "0.29"
serde_yaml = "0.9"
pipewire = "0.8"
wayland-client = "0.31.5"
wayland-protocols = { version = "0.32.3", features = ["client", "unstable"] }
itertools = "0.13"
hex_color = { version = "3.0", features = ["serde"] }
anyhow = "1"
