name: Nix CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  checks-build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v28
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build
